name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Backend Setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        run: |
          pip install -r requirements.txt
          pip install httpx
          cd backend
          pip install pytest fastapi uvicorn torch pandas numpy opencv-python 

      - name: Run Backend Server in Background
        run: |
          cd backend
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &

      - name: Run Backend Tests
        run: |
          cd backend
          pytest test_app.py

      # Frontend Setup
      - name: Install Frontend
        run: |
          cd frontend
          nohup python3 -m http.server 8001 &  # Serve the frontend for testing

      - name: Validate Frontend-Backend Connection
        run: |
          curl -X POST "http://localhost:8000/api/generate-ui" || echo "Backend API not reachable"
          curl -X GET "http://localhost:8001/home.html" || echo "Frontend not reachable"
          

  #deploy-backend:
  #  needs: build-and-test
  #  runs-on: ubuntu-latest
#
  #  steps:
  #    - name: Deploy Backend via SSH
  #      uses: appleboy/ssh-action@master
  #      with:
  #        host: ${{ secrets.SERVER_HOST }}
  #        username: ${{ secrets.SERVER_USER }}
  #        key: ${{ secrets.SSH_PRIVATE_KEY }}
  #        script: |
  #          cd /path/to/backend
  #          git pull origin main
  #          pip install -r requirements.txt
  #          systemctl restart backend.service || nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
#
#
  #deploy-frontend:
  #  needs: build-and-test
  #  runs-on: ubuntu-latest
#
  #  steps:
  #    - name: Deploy Frontend via SSH
  #      uses: appleboy/ssh-action@master
  #      with:
  #        host: ${{ secrets.SERVER_HOST }}
  #        username: ${{ secrets.SERVER_USER }}
  #        key: ${{ secrets.SSH_PRIVATE_KEY }}
  #        script: |
  #          cd /path/to/frontend
  #          git pull origin main
  #          nohup python3 -m http.server 8001 &